apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "golden-api.fullname" . }}
  labels:
    {{- include "golden-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "golden-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "golden-api.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ default "" (ternary (default (include "golden-api.fullname" .) .Values.serviceAccount.name) .Values.serviceAccount.name .Values.serviceAccount.create) }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: api
          image: "{{ include "golden-api.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          {{- if .Values.envFromConfigMap }}
          envFrom:
            - configMapRef:
                name: {{ .Values.envFromConfigMap }}
          {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}

          env:
            {{- toYaml .Values.env | nindent 12 }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}

      volumes:
        {{- toYaml .Values.extraVolumes | nindent 8 }}