apiVersion: v1
kind: Service
metadata:
  name: {{ include "golden-api.fullname" . }}
  labels:
    {{- include "golden-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "golden-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ default .Values.containerPort .Values.service.targetPort }}
      protocol: TCP